---
name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    name: Tests on ${{ matrix.system }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
            os: ubuntu-latest
          - system: aarch64-darwin
            os: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v12
      - uses: cachix/install-nix-action@v31
      - run: nix fmt
      - name: Run flake check
        run: nix flake check --system ${{ matrix.system }}
