---
name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    name: Tests on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64-darwin
          - x86_64-linux
    steps:
      - uses: actions/checkout@v4
      - name: Check nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v10
      - uses: cachix/install-nix-action@v31
      - name: Run flake check
        run: nix flake check --system ${{ matrix.arch }}
